//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Outer()
        {
            this.OuterOptions = new HashSet<OuterOptions>();
        }
    
        public int Outer_ID { get; set; }
        public int Polls_ID { get; set; }
        public Nullable<int> Outer_Rating { get; set; }
        public string Outer_Text { get; set; }
        public string Outer_Name { get; set; }
        public string OuterSes_ID { get; set; }
    
        public virtual Polls Polls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OuterOptions> OuterOptions { get; set; }
    }
}
