//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OuterOptions
    {
        public Nullable<int> Outer_ID { get; set; }
        public int Options_Outer_ID { get; set; }
        public Nullable<int> Options_ID { get; set; }
    
        public virtual Options Options { get; set; }
        public virtual Outer Outer { get; set; }
    }
}
