//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polls()
        {
            this.Options = new HashSet<Options>();
            this.Outer = new HashSet<Outer>();
        }
    
        public int Polls_ID { get; set; }
        public int Polls_Type_ID { get; set; }
        public string Polls_Name { get; set; }
        public int Event_ID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Rating { get; set; }
        public bool IsMulti { get; set; }
        public Nullable<int> MaxMulti { get; set; }
        public Nullable<int> LimitPerson { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Options> Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outer> Outer { get; set; }
        public virtual Polls_Type Polls_Type { get; set; }
    }
}
